### ISSUE TITLE
about the ap

### ISSUE THREAD

**Issue by Mixtrue** [vojirt/JSRNet#1]
dear author
when i train this model by running train.py  in my pc,i got the result of ap 18.7 which  is far below the result in your paper.i dont't modify your code and just running train.py,could you plz give me more infomation about the training details or release the well-trained model weight which can achieve the result in your papers.
thanks a alot

**Comment by vojirt** [comment]
Hi, did you download and used the segmentation model provided? You need to change the config to point to the location of the pretrained model as described in the readme file (section "Models"). I can provide the trained model that achieved the results in the paper on request for academic purpose only.

**Comment by Mixtrue** [comment]
thanks for your reply!
I repeat the training procedure but still got bad result. I download the segmentation model and modify the path in config/default.py.
Here i have&nbsp; some confusion. As written in the readme.md, we have two pretrained model&nbsp; which named segmentation.pth and best.pth.
I wonder whether the best.pth&nbsp;includes the weight of semantic segmentation model&nbsp;（segmentation.pth）
And here are my tensorboard log and some config parameters（just running the default train.py）






I just want to reproduce performance on my own device for the following research, but i always get bad training result.Could you give me&nbsp;
some more information about the training or release the well-trained model for reproducing the performance?
Thanks again sincerely!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vojirt/JSRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 晚上8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vojirt/JSRNet] about the ap (Issue #1)





 
Hi, did you download and used the segmentation model provided? You need to change the config to point to the location of the pretrained model as described in the readme file (section "Models"). I can provide the trained model that achieved the results in the paper on request for academic purpose only.

**Comment by vojirt** [comment]
Hi, 
without you providing any logs (output of the training) I can not help you more. What do you mean by "bad results"?
The code uses two models - one is for the semantic segmentation part and is fixed (the semantic segmentation network is not trained/fine-tuned) and the other model is the one that you train to detect the anomalies. 

If you send me an email (you can find my email here: https://cmp.felk.cvut.cz/~vojirtom/) requesting the trained model and stating that you will use it for research purpose only, I can send you the link to download it.

**Comment by Mixtrue** [comment]
Hi,
thanks for you patience, I&nbsp; have sent some log files of the training this time.
Bad results means the AP finally achieved about 17 during my training which is much lower than expected.
I do the training for twice but get similar result.
If you need other documents or information, please let me know and I will provide it immediately。
I'm sorry to have taken up your time，thanks for your help.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vojirt/JSRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vojirt/JSRNet] about the ap (Issue #1)





 
Hi,
 without you providing any logs (output of the training) I can not help you more. What do you mean by "bad results"?
 The code uses two models - one is for the semantic segmentation part and is fixed (the semantic segmentation network is not trained/fine-tuned) and the other model is the one that you train to detect the anomalies.
 
If you send me an email (you can find my email here: https://cmp.felk.cvut.cz/~vojirtom/) requesting the trained model and stating that you will use it for research purpose only, I can send you the link to download it.

**Comment by vojirt** [comment]
I don't see any logs attached. The training scripts save the console output to the "console.log" file, can you attach this file?

**Comment by Mixtrue** [comment]
I send these files again.

Can you see them in this email?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vojirt/JSRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 晚上7:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vojirt/JSRNet] about the ap (Issue #1)





 
I don't see any logs attached. The training scripts save the console output to the "console.log" file, can you attach this file?

**Comment by vojirt** [comment]
I did not receive any email from you. You can attach the file here.

**Comment by vojirt** [comment]
based on our email communication one of these points helped solving the issue:

here are three points ordered by priority that may effect the training. For testing purposes, I would recommend to try the original configuration and:
1) use full path when defining the path to the segmentation model checkpoint
2) I use single gpu for training, there is code for multi-gpu training, but it is not tested (also relates to the SYNC_BN parameter).
3) I used 100 epochs, it effects the LR scheduling so it may play some role
