### ISSUE TITLE
About the latent_dim in  ReconstructionDecoder's ASPP 

### ISSUE THREAD

**Issue by 448357739** [vojirt/JSRNet#2]
Dear author:
        The output dimension of Deeplabv3's ASSP is 256. The latent_dim in  ReconstructionDecoder's ASPP is set as 4, which means the  2056-dimensional features are reduced sharply  through ASPP in channel . Then in decoder ,the change in channel dimension is 4 ->128->64->16->3. I am confused about the latent_dim setting , can you just tell me the reason ?

**Comment by vojirt** [comment]
Hi, 
for details and reasoning you can refer to the publication. Briefly, this large reduction in dimensions is to create small enough bottleneck for the decoder to force it to learn only the road appearance that has inherently limited variance ("most roads look the same").
